### ISSUE TITLE
CRT Geometry Adjust Crash

### ISSUE THREAD

**Issue by jbawgs** [ZFEbHVUE/Batocera-CRT-Script#170]
CRT Geometry Adjustment application crashes back to ES with no error. I do not know how to log these events.

This is batocera 38, running your script on an r9 280 through VGA to a wakabavideo vga->component transcoder

**Comment by Smelly1sam** [comment]
I have the same issue with 37. Using a Radeon R7 350X with a wakabavideo vga to competent transcoder.

**Comment by jbawgs** [comment]
> I have the same issue with 37. Using a Radeon R7 350X with a wakabavideo vga to competent transcoder.

I figured out what's up. If you choose "ntsc" when you run the setup it will always close out. Choose one of the other 15khz modes and it works just fine.

**Comment by Smelly1sam** [comment]
> > I have the same issue with 37. Using a Radeon R7 350X with a wakabavideo vga to competent transcoder.
> 
> I figured out what's up. If you choose "ntsc" when you run the setup it will always close out. Choose one of the other 15khz modes and it works just fine.

Thank you, I had also used NTSC. Will try the other option when I get a chance.

**Comment by Smelly1sam** [comment]
Generic 15 worked for me

**Comment by willsy32** [comment]
Same issue with an Nvidia 980.  Using arcade 15khz.

**Comment by Redemp** [comment]
@Smelly1sam @jbawgs @willsy32 
Working on it. 
New CRT Geometry script is in the works.
Also check out the new updated script for changes :)

**Comment by Smelly1sam** [comment]
> @Smelly1sam @jbawgs @willsy32 Working on it. New CRT Geometry script is in the works. Also check out the new updated script for changes :)

Thank you for the continued work!

**Comment by Redemp** [comment]
**Update for the script**

* Added the ES Tool for Centering
* Added the new CRT Geometry Script
* Added some info in the wiki if you would like to contribute
