### ISSUE TITLE
Intructions lead to you to doing restore

### ISSUE THREAD

**Issue by Smelly1sam** [ZFEbHVUE/Batocera-CRT-Script#209]
I just installed v39 and went to use the script for the first time. It prompted me saying there was a restore that was possible. I followed the instructions step by step:

`cd /userdata/system/Batocera-CRT-Script/Batocera_ALLINONE`

`chmod 755 Batocera-CRT-Script.sh`

`./Batocera-CRT-Script.sh` 

Saying no to the restore allowed it to work correctly

**Comment by Redemp** [comment]
https://github.com/ZFEbHVUE/Batocera-CRT-Script/pull/205
