### ISSUE TITLE
emulationstation aspect ratio wrong

### ISSUE THREAD

**Issue by KaiRamiel** [ZFEbHVUE/Batocera-CRT-Script#212]
The aspect ratio of emulationstation is compressed horizontally. How can I adjust this? It's as if there is a super resolution like 1920x480. i am using batocera v38 with intel graphics.  how can i set a proper 4:3?
![DSC_6603](https://github.com/ZFEbHVUE/Batocera-CRT-Script/assets/168307147/b6f9d8b1-1ed4-4e50-916b-836d5595a331)

**Comment by Redemp** [comment]
No support for v38. 
We only support the latest release.
See links here 
https://github.com/ZFEbHVUE/Batocera-CRT-Script/blob/main/HowTo_Wired_Or_Wireless_Connection.md
https://github.com/ZFEbHVUE/Batocera-CRT-Script/wiki
