### ISSUE TITLE
Script not working on my PC

### ISSUE THREAD

**Issue by Non0Nan0** [ZFEbHVUE/Batocera-CRT-Script#242]
Hello everyone,
I need to force the video output to 15KHz in order to make Batocera work with an old-fashioned coin-op. In order to achieve this I'm using your script. My processor is Intel® Pentium® Processor E5500 2M Cache, 2.80 GHz, 800 MHz FSB (64bit). My graphic card is: AMD/ATI  Radeon HD4650 VGA controller. I've tried Batocera v32 and v33. I've tried to install batocera both in an ssd and hdd multiple times. The script runs correctly (saying that my graphic card is ready to work at that frequency) but when I reload the system I get the following boot error: https://ibb.co/DkLWJ6L. 
I've checked issue #2 but I'm not sure it applies to my case since I've tried both AMDGPU and RADEON choices and the result is te same.
I must say that when I reload the system I still use the LCD monitor..I know that it is wrong but with another PC where the script ran correctly it happened that on the LCD monitor I could see a completely different video output (supposly 15KHz) and not the error I'm getting in this case.
This project is very important to me, I really would like to make that old coin-op live again. Thanks for you help!

P.s. I'm attaching also the choices that I'm making inside the script

[Batocera configuration.pdf](https://github.com/user-attachments/files/16626297/Batocera.configuration.pdf)

**Comment by Redemp** [comment]
Using old version of the script not supported nor available on the GitHub page. Closing.
