### ISSUE TITLE
/Batocera-CRT-Script-v40.sh: Permission denied

### ISSUE THREAD

**Issue by sishenzhisi** [ZFEbHVUE/Batocera-CRT-Script#249]
/Batocera-CRT-Script-v40.sh: Permission denied What to do

**Comment by Redemp** [comment]
You didn't follow the installation instructions from the main pagr

**Comment by ZFEbHVUE** [comment]
chmod 755 ~/Batocera-CRT-Script/Batocera_ALLINONE/Batocera-CRT-Script-v40.sh

**Comment by Redemp** [comment]
Closing this as it's just a user error.
