### ISSUE TITLE
pls add 31k@120hz script.

### ISSUE THREAD

**Issue by greatliu** [ZFEbHVUE/Batocera-CRT-Script#51]
Hi, sir.
Can you support a new script of 31k@120hz for old crt monitor users?
Thanks.

**Comment by Redemp** [comment]
Hi. 
Join the Batocera Discord and send me a DM and we can see what we can do :)

**Comment by greatliu** [comment]
Sorry, I am in China and cannot visit discord.
I have achieved ***@***.*** by changing the monitor type to pc_31_120.
I think there are many crt monitor users need this scripts.

Thanks.



***@***.***
 
From: Rion
Date: 2022-11-30 04:13
To: ZFEbHVUE/Build-CRT-15KHz-Batocera-V35
CC: greatliu; Author
Subject: Re: [ZFEbHVUE/Build-CRT-15KHz-Batocera-V35] pls add ***@***.*** script. (Issue #51)
Hi.
Join the Batocera Discord and send me a DM and we can see what we can do :)

**Comment by Redemp** [comment]
I don't have any eta on when this will be supported but it will at some point.
looking to get some help from users with a PC Crt since I nor any of the others devs have one.

**Comment by ZFEbHVUE** [comment]
Hi greatliu

I have update this script with 25KHz and 31KHz. I did it since december 2022 but without 31KHz monitor I didn't do tests

**Comment by ZFEbHVUE** [comment]
Hello Greatliu.

When you spoke about yellow letters, you means on Retroarch. I think we need to modify
the value /userdata/system/batocera.conf  :     global.retroarch.video_font_size = 10 is the default 
try to put 20 even more to see what's happen.

Thx to testing.

ZFEbHVUE.

**Comment by pys200603027** [comment]
I found a solution
1. You run the script once and select 31kHz in the frequency options
2. Log in to Btocera using SSH
3. Modify the /etc/switchres .ini
`	monitor                   arcade_31` 
`arcade_31` to `pc_31_120`
4. Modify the boot boot resolution 
1) run `mount -o remount, rw /boot`
2) Find `/boot/EFI/syslinux.cfg` and `/boot/boot/syslinux/syslinux.cfg`
3) modify `edid/arcade_31.bin` to  `edid/pc_31_120.bin`

> make sure `pc_31_120.bin` is in `/lib/firmware/edid/`

4) run `batocera-save-overlay`
5. reboot

**Comment by Redemp** [comment]
@greatliu @pys200603027 
Done! 
See updated script on github :)
